//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ALMAL_Freelancer.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ALMAL_FreelancerDBEntities : DbContext
    {
        public ALMAL_FreelancerDBEntities()
            : base("name=ALMAL_FreelancerDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<tblAcademicBackground> tblAcademicBackgrounds { get; set; }
        public virtual DbSet<tblAdminProfile> tblAdminProfiles { get; set; }
        public virtual DbSet<tblAlert> tblAlerts { get; set; }
        public virtual DbSet<tblAvailabilityConfig> tblAvailabilityConfigs { get; set; }
        public virtual DbSet<tblExperience> tblExperiences { get; set; }
        public virtual DbSet<tblFeaturedProfile> tblFeaturedProfiles { get; set; }
        public virtual DbSet<tblLocationRegistry> tblLocationRegistries { get; set; }
        public virtual DbSet<tblMedia> tblMedias { get; set; }
        public virtual DbSet<tblMissionType> tblMissionTypes { get; set; }
        public virtual DbSet<tblMobilityConfig> tblMobilityConfigs { get; set; }
        public virtual DbSet<tblProfessionalDocument> tblProfessionalDocuments { get; set; }
        public virtual DbSet<tblRecommendation> tblRecommendations { get; set; }
        public virtual DbSet<tblRemuneration> tblRemunerations { get; set; }
        public virtual DbSet<tblRoleConfig> tblRoleConfigs { get; set; }
        public virtual DbSet<tblSkillConfig> tblSkillConfigs { get; set; }
        public virtual DbSet<tblSocialConnection> tblSocialConnections { get; set; }
        public virtual DbSet<tblSubscription> tblSubscriptions { get; set; }
        public virtual DbSet<tblUserMissionType> tblUserMissionTypes { get; set; }
        public virtual DbSet<tblUserPhoto> tblUserPhotoes { get; set; }
        public virtual DbSet<tblUserProfile> tblUserProfiles { get; set; }
        public virtual DbSet<tblUserSkill> tblUserSkills { get; set; }
        public virtual DbSet<tblSystemAnomaly> tblSystemAnomalies { get; set; }
        public virtual DbSet<tblTicket> tblTickets { get; set; }
    }
}
