//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ALMAL_Freelancer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAcademicBackground
    {
        public int AcademicBackgroundID { get; set; }
        public Nullable<int> UserProfileID { get; set; }
        public string School { get; set; }
        public string Department { get; set; }
        public string StartDate { get; set; }
        public string StopDate { get; set; }
        public Nullable<bool> IsGraduated { get; set; }
        public string Description { get; set; }
    
        public virtual tblUserProfile tblUserProfile { get; set; }
    }
}
