//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ALMAL_Freelancer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblMissionType
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblMissionType()
        {
            this.tblAlerts = new HashSet<tblAlert>();
            this.tblFeaturedProfiles = new HashSet<tblFeaturedProfile>();
            this.tblUserMissionTypes = new HashSet<tblUserMissionType>();
        }
    
        public int MissionTypeID { get; set; }
        public Nullable<int> MobilityConfigID { get; set; }
        public string Subject { get; set; }
        public string Description { get; set; }
        public Nullable<int> Amount { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsCompleted { get; set; }
        public string EstimatedStartTime { get; set; }
        public string EstimatedStopTime { get; set; }
        public string StartDuration { get; set; }
        public string StopDuration { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblAlert> tblAlerts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblFeaturedProfile> tblFeaturedProfiles { get; set; }
        public virtual tblMobilityConfig tblMobilityConfig { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblUserMissionType> tblUserMissionTypes { get; set; }
    }
}
