//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ALMAL_Freelancer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblProfessionalDocument
    {
        public int ProfessionalDocumentID { get; set; }
        public Nullable<int> UserProfileID { get; set; }
        public string FrontNicUrl { get; set; }
        public string BackNicUrl { get; set; }
        public string FrontDriverLicenseUrl { get; set; }
        public string BackDriverLicenseUrl { get; set; }
        public string PassportUrl { get; set; }
        public string RegDate { get; set; }
    
        public virtual tblUserProfile tblUserProfile { get; set; }
    }
}
