//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ALMAL_Freelancer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSystemAnomaly
    {
        public int SystemAnomalyID { get; set; }
        public string Analysis { get; set; }
        public string Timeline { get; set; }
        public string Description { get; set; }
        public string SectionUrl { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<bool> IsRead { get; set; }
    
        public virtual tblAdminProfile tblAdminProfile { get; set; }
        public virtual tblUserProfile tblUserProfile { get; set; }
    }
}
