//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ALMAL_Freelancer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSocialConnection
    {
        public int SocialConnectionID { get; set; }
        public Nullable<int> UserProfileID { get; set; }
        public Nullable<int> CoonectionUserID { get; set; }
        public Nullable<int> IsCollab { get; set; }
        public Nullable<bool> IsFollow { get; set; }
        public Nullable<bool> IsFollowing { get; set; }
        public Nullable<bool> IsRecommend { get; set; }
    
        public virtual tblUserProfile tblUserProfile { get; set; }
        public virtual tblUserProfile tblUserProfile1 { get; set; }
    }
}
