//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ALMAL_Freelancer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblTicket
    {
        public int TicketID { get; set; }
        public Nullable<int> UserProfileID { get; set; }
        public Nullable<int> RepliedBy { get; set; }
        public string Subject { get; set; }
        public string Description { get; set; }
        public string ContentUrl { get; set; }
        public Nullable<bool> IsRead { get; set; }
    
        public virtual tblAdminProfile tblAdminProfile { get; set; }
        public virtual tblUserProfile tblUserProfile { get; set; }
    }
}
