//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ALMAL_Freelancer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblUserSkill
    {
        public int UserSkillID { get; set; }
        public Nullable<int> UserProfileID { get; set; }
        public Nullable<int> SkillConfigID { get; set; }
        public Nullable<int> Progress { get; set; }
    
        public virtual tblSkillConfig tblSkillConfig { get; set; }
        public virtual tblUserProfile tblUserProfile { get; set; }
    }
}
