//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ALMAL_Freelancer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblUserMissionType
    {
        public int UserMissionTypeID { get; set; }
        public Nullable<int> MissionTypeID { get; set; }
        public Nullable<int> UserProfileID { get; set; }
        public string StartDate { get; set; }
        public string StopDate { get; set; }
        public Nullable<bool> IsCompleted { get; set; }
    
        public virtual tblMissionType tblMissionType { get; set; }
        public virtual tblUserProfile tblUserProfile { get; set; }
    }
}
