//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ALMAL_Freelancer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblUserProfile
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblUserProfile()
        {
            this.tblAcademicBackgrounds = new HashSet<tblAcademicBackground>();
            this.tblAlerts = new HashSet<tblAlert>();
            this.tblExperiences = new HashSet<tblExperience>();
            this.tblFeaturedProfiles = new HashSet<tblFeaturedProfile>();
            this.tblMedias = new HashSet<tblMedia>();
            this.tblProfessionalDocuments = new HashSet<tblProfessionalDocument>();
            this.tblRecommendations = new HashSet<tblRecommendation>();
            this.tblRemunerations = new HashSet<tblRemuneration>();
            this.tblSocialConnections = new HashSet<tblSocialConnection>();
            this.tblSocialConnections1 = new HashSet<tblSocialConnection>();
            this.tblUserMissionTypes = new HashSet<tblUserMissionType>();
            this.tblUserSkills = new HashSet<tblUserSkill>();
            this.tblSystemAnomalies = new HashSet<tblSystemAnomaly>();
            this.tblTickets = new HashSet<tblTicket>();
        }
    
        public int UserProfileID { get; set; }
        public string FullName { get; set; }
        public string UserName { get; set; }
        public string Email { get; set; }
        public string Tel { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public string Password { get; set; }
        public Nullable<int> EmailVerificationCode { get; set; }
        public Nullable<bool> IsEmailVerificationCode { get; set; }
        public string Biography { get; set; }
        public Nullable<int> UserPhotoID { get; set; }
        public string AccountUrl { get; set; }
        public Nullable<int> MobilityConfigID { get; set; }
        public Nullable<int> LocationRegistryID { get; set; }
        public Nullable<int> AvailabilityConfigID { get; set; }
        public Nullable<bool> IsVerified { get; set; }
        public Nullable<int> SubscriptionID { get; set; }
        public Nullable<System.DateTime> SubscriptionExpiryDate { get; set; }
        public Nullable<bool> IsSubscriptionExpired { get; set; }
        public Nullable<bool> IsOnline { get; set; }
        public Nullable<bool> IsBlocked { get; set; }
        public string RegDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblAcademicBackground> tblAcademicBackgrounds { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblAlert> tblAlerts { get; set; }
        public virtual tblAvailabilityConfig tblAvailabilityConfig { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblExperience> tblExperiences { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblFeaturedProfile> tblFeaturedProfiles { get; set; }
        public virtual tblLocationRegistry tblLocationRegistry { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblMedia> tblMedias { get; set; }
        public virtual tblMobilityConfig tblMobilityConfig { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblProfessionalDocument> tblProfessionalDocuments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblRecommendation> tblRecommendations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblRemuneration> tblRemunerations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblSocialConnection> tblSocialConnections { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblSocialConnection> tblSocialConnections1 { get; set; }
        public virtual tblSubscription tblSubscription { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblUserMissionType> tblUserMissionTypes { get; set; }
        public virtual tblUserPhoto tblUserPhoto { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblUserSkill> tblUserSkills { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblSystemAnomaly> tblSystemAnomalies { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblTicket> tblTickets { get; set; }
    }
}
